version: 2.1

jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - run: go version
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go test -v ./...
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

  integration-test:
    docker:
      - image: 'circleci/python:3-stretch'
    environment:
      TEST_BINARY: ~/project/trellis-cli
    steps:
      - run: python --version
      - checkout
      - restore_cache:
          keys:
            - ansible-v1-{{ checksum "requirements.yml" }}
      - run:
          name: Install Ansible in a venv
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install ansible~=2.7.0
            ansible --version
      - run:
          name: Install Galaxy roles
          command: |
            . venv/bin/activate
            ansible-galaxy install -r requirements.yml
          working_directory: cmd/testdata/trellis
      - save_cache:
          key: ansible-v1-{{ checksum "requirements.yml" }}
          paths:
            - venv
            - cmd/testdata/trellis/vendor

      # Install go
      - run: wget https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz
      - run: sudo tar -xvf go1.12.7.linux-amd64.tar.gz
      - run: sudo mv go /usr/local
      - run: go version

      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go build
      - run: go test -v --tag=integration ./...
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - run: go version
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  test:
    jobs:
      - test
      - integration-test
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
