name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Test
        run: go test -v -short ./...

  release-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: anchore/sbom-action/download-syft@v0
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true
      - name: Check release (dry-run)
        run: |
          goreleaser check
          goreleaser release --snapshot --clean --skip publish
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_ACCESS_TOKEN }}

  integration-test:
    runs-on: ubuntu-latest
    container:
      image: rootsdev/trellis-cli-dev
    steps:
      - run: go version
      - run: ansible --version
      - name: Trellis version
        run: git log -1 --format="%h %s %aD"
        working-directory: /test/dummy/trellis
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Tests
        run: make test RUN=
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trellis-cli
          path: /test/trellis-cli
